/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class meshgui_Home */

#ifndef _Included_meshgui_Home
#define _Included_meshgui_Home
#ifdef __cplusplus
extern "C" {
#endif
#undef meshgui_Home_FOCUS_TRAVERSABLE_UNKNOWN
#define meshgui_Home_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef meshgui_Home_FOCUS_TRAVERSABLE_DEFAULT
#define meshgui_Home_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef meshgui_Home_FOCUS_TRAVERSABLE_SET
#define meshgui_Home_FOCUS_TRAVERSABLE_SET 2L
#undef meshgui_Home_TOP_ALIGNMENT
#define meshgui_Home_TOP_ALIGNMENT 0.0f
#undef meshgui_Home_CENTER_ALIGNMENT
#define meshgui_Home_CENTER_ALIGNMENT 0.5f
#undef meshgui_Home_BOTTOM_ALIGNMENT
#define meshgui_Home_BOTTOM_ALIGNMENT 1.0f
#undef meshgui_Home_LEFT_ALIGNMENT
#define meshgui_Home_LEFT_ALIGNMENT 0.0f
#undef meshgui_Home_RIGHT_ALIGNMENT
#define meshgui_Home_RIGHT_ALIGNMENT 1.0f
#undef meshgui_Home_serialVersionUID
#define meshgui_Home_serialVersionUID -7644114512714619750LL
#undef meshgui_Home_serialVersionUID
#define meshgui_Home_serialVersionUID 4613797578919906343LL
#undef meshgui_Home_INCLUDE_SELF
#define meshgui_Home_INCLUDE_SELF 1L
#undef meshgui_Home_SEARCH_HEAVYWEIGHTS
#define meshgui_Home_SEARCH_HEAVYWEIGHTS 1L
#undef meshgui_Home_OPENED
#define meshgui_Home_OPENED 1L
#undef meshgui_Home_serialVersionUID
#define meshgui_Home_serialVersionUID 4497834738069338734LL
#undef meshgui_Home_DEFAULT_CURSOR
#define meshgui_Home_DEFAULT_CURSOR 0L
#undef meshgui_Home_CROSSHAIR_CURSOR
#define meshgui_Home_CROSSHAIR_CURSOR 1L
#undef meshgui_Home_TEXT_CURSOR
#define meshgui_Home_TEXT_CURSOR 2L
#undef meshgui_Home_WAIT_CURSOR
#define meshgui_Home_WAIT_CURSOR 3L
#undef meshgui_Home_SW_RESIZE_CURSOR
#define meshgui_Home_SW_RESIZE_CURSOR 4L
#undef meshgui_Home_SE_RESIZE_CURSOR
#define meshgui_Home_SE_RESIZE_CURSOR 5L
#undef meshgui_Home_NW_RESIZE_CURSOR
#define meshgui_Home_NW_RESIZE_CURSOR 6L
#undef meshgui_Home_NE_RESIZE_CURSOR
#define meshgui_Home_NE_RESIZE_CURSOR 7L
#undef meshgui_Home_N_RESIZE_CURSOR
#define meshgui_Home_N_RESIZE_CURSOR 8L
#undef meshgui_Home_S_RESIZE_CURSOR
#define meshgui_Home_S_RESIZE_CURSOR 9L
#undef meshgui_Home_W_RESIZE_CURSOR
#define meshgui_Home_W_RESIZE_CURSOR 10L
#undef meshgui_Home_E_RESIZE_CURSOR
#define meshgui_Home_E_RESIZE_CURSOR 11L
#undef meshgui_Home_HAND_CURSOR
#define meshgui_Home_HAND_CURSOR 12L
#undef meshgui_Home_MOVE_CURSOR
#define meshgui_Home_MOVE_CURSOR 13L
#undef meshgui_Home_NORMAL
#define meshgui_Home_NORMAL 0L
#undef meshgui_Home_ICONIFIED
#define meshgui_Home_ICONIFIED 1L
#undef meshgui_Home_MAXIMIZED_HORIZ
#define meshgui_Home_MAXIMIZED_HORIZ 2L
#undef meshgui_Home_MAXIMIZED_VERT
#define meshgui_Home_MAXIMIZED_VERT 4L
#undef meshgui_Home_MAXIMIZED_BOTH
#define meshgui_Home_MAXIMIZED_BOTH 6L
#undef meshgui_Home_serialVersionUID
#define meshgui_Home_serialVersionUID 2673458971256075116LL
#undef meshgui_Home_EXIT_ON_CLOSE
#define meshgui_Home_EXIT_ON_CLOSE 3L
/*
 * Class:     meshgui_Home
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_init
  (JNIEnv *, jclass);

/*
 * Class:     meshgui_Home
 * Method:    security
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_security
  (JNIEnv *, jclass, jint);

/*
 * Class:     meshgui_Home
 * Method:    discoverUnprovisioned
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_discoverUnprovisioned
  (JNIEnv *, jclass, jint);

/*
 * Class:     meshgui_Home
 * Method:    provision
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_provision
  (JNIEnv *, jclass, jstring);

/*
 * Class:     meshgui_Home
 * Method:    appKeyAdd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_appKeyAdd
  (JNIEnv *, jclass, jint);

/*
 * Class:     meshgui_Home
 * Method:    appKeyBind
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_appKeyBind
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     meshgui_Home
 * Method:    removeNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_removeNode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     meshgui_Home
 * Method:    onoff
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_onoff
  (JNIEnv *, jclass, jint);

/*
 * Class:     meshgui_Home
 * Method:    hsl
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_hsl
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     meshgui_Home
 * Method:    ctl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_ctl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     meshgui_Home
 * Method:    lightness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_lightness
  (JNIEnv *, jclass, jint);

/*
 * Class:     meshgui_Home
 * Method:    level
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_meshgui_Home_level
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
