/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meshgui;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author ledvance
 */

public class DeviceControl extends javax.swing.JFrame {
    
    /*static {                                                                     
         try {                                                                  
            System.loadLibrary( "onoffModel" );
            System.loadLibrary( "HSLModel" );
            System.loadLibrary( "CTLModel" );
            System.loadLibrary( "lightnessModel" );
            System.loadLibrary( "removeNode" );
         }                                                                      
         catch( UnsatisfiedLinkError e ) {                                      
            System.out.println(                                                 
               "Could not load native code :(" ); 
            System.exit(1);                                                     
         }                                                                      
   }*/

    public final String SELECTED_DEVICE;
    ImageIcon colorWheel = new ImageIcon("colorwheel_only.png");
    
    /**
     * Creates new form DeviceControl
     * @param device
     */
    public DeviceControl( String device ) {
        initComponents();
        SELECTED_DEVICE = device;
        controllingLabel.setText( "Controlling " + device );
        onoffBtn.setSelected( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controllingLabel = new javax.swing.JLabel();
        onoffBtn = new javax.swing.JToggleButton();
        colorDiamond = new javax.swing.JLabel();
        brightnessSlider = new javax.swing.JSlider();
        cctColorBtn = new javax.swing.JToggleButton();
        closeBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controllingLabel.setText("Controlling ");

        onoffBtn.setText("ON");
        onoffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onoffBtnMouseClicked(evt);
            }
        });

        colorDiamond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meshgui/colorwheel_only.png"))); // NOI18N
        colorDiamond.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                colorDiamondMouseDragged(evt);
            }
        });

        brightnessSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brightnessSliderStateChanged(evt);
            }
        });

        cctColorBtn.setText("CCT");
        cctColorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cctColorBtnMouseClicked(evt);
            }
        });

        closeBtn.setText("Close");

        removeBtn.setText("Remove");
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(colorDiamond))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(cctColorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(brightnessSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(onoffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBtn)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controllingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controllingLabel)
                    .addComponent(removeBtn))
                .addGap(19, 19, 19)
                .addComponent(onoffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brightnessSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorDiamond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cctColorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onoffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onoffBtnMouseClicked
        if( onoffBtn.isSelected() )
        {
            colorDiamond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meshgui/blank.png")));
            onoffBtn.setText( "ON" );
        }
        else
        {
            colorDiamond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meshgui/colorwheel_only.png")));
            onoffBtn.setText("OFF" );
        }
        
    }//GEN-LAST:event_onoffBtnMouseClicked

    private void brightnessSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brightnessSliderStateChanged

        //System.out.println(jSlider1.getValue());
        
    }//GEN-LAST:event_brightnessSliderStateChanged

    private void cctColorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cctColorBtnMouseClicked
        if( cctColorBtn.isSelected() )
        {
            
            cctColorBtn.setText( "Color" );
        }
        else
        {
            cctColorBtn.setText("CCT" );
        }
    }//GEN-LAST:event_cctColorBtnMouseClicked

    private void colorDiamondMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorDiamondMouseDragged
        //System.out.println( "Angle: " + getAngle( evt.getX(), evt.getY()) );
        //System.out.println( "GetX: " + evt.getX() + " GetY: " + evt.getY() );
        //System.out.println( "GetXOnScreen: " + evt.getXOnScreen() + " GetYOnScreen: " + evt.getYOnScreen() );
    }//GEN-LAST:event_colorDiamondMouseDragged

    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnMouseClicked

    private double getAngle( double xTouch, double yTouch )
    {
        int diamondWidth, diamondHeight;
        diamondWidth = colorWheel.getIconWidth();
        diamondHeight = colorWheel.getIconHeight();
        double x = xTouch - (diamondWidth / 2d );
        double y = diamondHeight - yTouch - (diamondHeight / 2d);
        return ((Math.toDegrees(Math.atan2(y, x))) + 360) % 360;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeviceControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeviceControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeviceControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider brightnessSlider;
    private javax.swing.JToggleButton cctColorBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel colorDiamond;
    private javax.swing.JLabel controllingLabel;
    private javax.swing.JToggleButton onoffBtn;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
